version: '3'

services:
  app:
    container_name: $CONTAINER_NAME
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - WORKDIR=$WORK_DIR
    tty: true
    env_file:
      - ./.env
    volumes:
      - .:$WORK_DIR:ro
