version: '3'

services:
  app:
    command: sleep infinity
    volumes:
      - .:$WORK_DIR:cached
      - pip-volume:$WORK_DIR/vendor
      - vscode-extension-volume:$HOME_DIR/.vscode-server/extensions

volumes:
  pip-volume:
  vscode-extension-volume: {}
