version: '3'

services:
  app:
    command: sleep infinity
    volumes:
      - .:/workspace:cached
      - pip-volume:/workspace/vendor
      - vscode-extension-volume:/root/.vscode-server/extensions

volumes:
  pip-volume:
  vscode-extension-volume: {}
